version: '3'

services:

  # yii2
  yii:
    image: ${YII2_IMAGE_NAME}:${YII2_IMAGE_VERSION}
    volumes:
      -  yii2-vol:/var/www/html
    ports:
      - '8000:80'
    networks:
      - yii2network

  # MySQL
  mysql:
    image: ${MYSQL_IMAGE_NAME}:${MYSQL_IMAGE_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - yii2network

networks:
  yii2network:

volumes:
  yii2-vol:
    driver: local
    driver_opts:
      type: none
      device: /app
      o: bind
